import * as wjcCore from '@grapecity/wijmo'
import '@grapecity/wijmo.vue2.core'
import '@grapecity/wijmo.vue2.input'
import '@grapecity/wijmo.vue2.grid'
import '@grapecity/wijmo.vue2.grid.sheet'
import '@grapecity/wijmo.vue2.grid.filter'
import '@grapecity/wijmo.vue2.gauge'
import '@grapecity/wijmo.vue2.chart'
import '@grapecity/wijmo.vue2.chart.interaction'
import '@grapecity/wijmo.vue2.chart.finance'
import '@grapecity/wijmo.vue2.chart.annotation'
import '@grapecity/wijmo.vue2.chart.animation'
import '@grapecity/wijmo.vue2.chart.analytics'
import '@grapecity/wijmo.vue2.chart.hierarchical'
// import '../node_modules/wijmo.all.latest/node_modules/@grapecity/wijmo.vue2.chart'
// import '../node_modules/wijmo.all.latest/node_modules/@grapecity/wijmo.vue2.chart.interaction'
// import '../node_modules/wijmo.all.latest/node_modules/@grapecity/wijmo.vue2.chart.finance'
// import '../node_modules/wijmo.all.latest/node_modules/@grapecity/wijmo.vue2.chart.annotation'
// import '../node_modules/wijmo.all.latest/node_modules/@grapecity/wijmo.vue2.chart.animation'
// import '../node_modules/wijmo.all.latest/node_modules/@grapecity/wijmo.vue2.chart.analytics'
// import '../node_modules/wijmo.all.latest/node_modules/@grapecity/wijmo.vue2.chart.hierarchical'

export default wjcCore
